# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GSPASS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GSPASS
  pod 'SwiftLint'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Alamofire', '~> 5.2'
  pod 'RxAlamofire'  
  pod 'KeychainSwift', '~> 19.0'
  pod 'Loaf'

end
